name = "TableOperations"
uuid = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "0.2.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Tables = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
